[package]
name = "fhe_orderbook"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "1.3.3"
axum = { version = "0.7", features = ["macros"] }
tokio = { version = "1.0", features = ["full","test-util", "macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"